"""Remove popup position - always center

Revision ID: 4f7f6fa7856c
Revises: cfb4a123707e
Create Date: 2025-12-14 10:12:42.469996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7f6fa7856c'
down_revision = 'cfb4a123707e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popups', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
