"""empty message

Revision ID: c0dfb662488d
Revises: 4f7f6fa7856c
Create Date: 2025-12-16 15:17:28.499737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dfb662488d'
down_revision = '4f7f6fa7856c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wizards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wizard_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizard_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('recommended_products', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wizard_id'], ['wizards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizard_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wizard_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wizard_id'], ['wizards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wizard_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['wizard_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wizard_options')
    op.drop_table('wizard_steps')
    op.drop_table('wizard_results')
    op.drop_table('wizards')
    # ### end Alembic commands ###
