"""Simplify popup - image only

Revision ID: cfb4a123707e
Revises: 95f0ada3ad73
Create Date: 2025-12-14 09:05:03.424534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb4a123707e'
down_revision = '95f0ada3ad73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('cta_link')
        batch_op.drop_column('description')
        batch_op.drop_column('cta_text')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cta_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('link')

    # ### end Alembic commands ###
