"""empty message

Revision ID: e6cbe5f5824c
Revises: e949b13a0b25
Create Date: 2025-12-13 10:55:36.858482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6cbe5f5824c'
down_revision = 'e949b13a0b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_guides_created_at'))
        batch_op.drop_index(batch_op.f('ix_installation_guides_is_active'))
        batch_op.drop_index(batch_op.f('ix_installation_guides_slug'))

    op.drop_table('installation_guides')
    with op.batch_alter_table('color_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_color_charts_is_active'))
        batch_op.drop_index(batch_op.f('ix_color_charts_slug'))

    op.drop_table('color_charts')
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('map_iframe', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('map_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('distributor_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_distributors_is_active'))
        batch_op.create_index(batch_op.f('ix_distributors_slug'), ['slug'], unique=True)
        batch_op.drop_column('image')
        batch_op.drop_column('services')
        batch_op.drop_column('order')
        batch_op.drop_column('province')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('services', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_distributors_slug'))
        batch_op.create_index(batch_op.f('ix_distributors_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('distributor_type')
        batch_op.drop_column('map_url')
        batch_op.drop_column('map_iframe')
        batch_op.drop_column('city')
        batch_op.drop_column('ward')
        batch_op.drop_column('website')
        batch_op.drop_column('slug')

    op.create_table('color_charts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('product_line', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('catalogue_file', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('color_codes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specifications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('color_charts_pkey'))
    )
    with op.batch_alter_table('color_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_color_charts_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_color_charts_is_active'), ['is_active'], unique=False)

    op.create_table('installation_guides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('excerpt', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('materials_needed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tools_needed', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('warnings', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('related_products', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('installation_guides_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('installation_guides_pkey'))
    )
    with op.batch_alter_table('installation_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_guides_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_guides_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_guides_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
