"""Add resources tables: distributors, color_charts, installation_guides

Revision ID: e949b13a0b25
Revises: 831bcff0bf6d
Create Date: 2025-12-11 15:48:31.445328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e949b13a0b25'
down_revision = '831bcff0bf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('product_line', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('catalogue_file', sa.String(length=500), nullable=True),
    sa.Column('color_codes', sa.JSON(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('color_charts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_color_charts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_color_charts_slug'), ['slug'], unique=True)

    op.create_table('distributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('working_hours', sa.String(length=200), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributors_is_active'), ['is_active'], unique=False)

    op.create_table('installation_guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('materials_needed', sa.JSON(), nullable=True),
    sa.Column('tools_needed', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('related_products', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation_guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_guides_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_guides_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_guides_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation_guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_guides_slug'))
        batch_op.drop_index(batch_op.f('ix_installation_guides_is_active'))
        batch_op.drop_index(batch_op.f('ix_installation_guides_created_at'))

    op.drop_table('installation_guides')
    with op.batch_alter_table('distributors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributors_is_active'))

    op.drop_table('distributors')
    with op.batch_alter_table('color_charts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_color_charts_slug'))
        batch_op.drop_index(batch_op.f('ix_color_charts_is_active'))

    op.drop_table('color_charts')
    # ### end Alembic commands ###
